### ISSUE TITLE
Issue with login using integration user's current person

### ISSUE THREAD

**Issue by burkesimmons** [york-solutions/fs-sample-app#1]
It's probably just me, I'm new to this (currently in a bootcamp right now).
Trying to accomplish this authentication and keep receiving "Username or Password Incorrect" from family search login page.
Help if you have time would be apprecieated.

**Comment by misbach** [comment]
Is your app key enabled for the username and password flow? What reference database is your code pointing to (production, beta, integration), and are you using the appropriate credentials for that reference?

**Comment by justincy** [comment]
@burkesimmons You're most likely trying to use your regular production account credentials on the integration (sandbox) system. You'll need to [register as a developer](https://familysearch.org/developers/) to get a login for the integration system.

**Comment by burkesimmons** [comment]
I have an app key, and an integration sandbox account username and
password. I'm getting an error trying to sign in with that account. Maybe I
need to contact someone else for help, but this is the username and
password I recieved:

URL: https://integration.familysearch.org
<https://integration.familysearch.org/>
Username: tuf000147398
Password: 1234pass

**Comment by burkesimmons** [comment]
I'm registered and they gave me the following which is not working. Any
ideas?
URL: https://integration.familysearch.org
<https://integration.familysearch.org/>
Username: tuf000147398
Password: 1234pass

**Comment by misbach** [comment]
Those credentials work fine on integration.familysearch.org. Do you have a URL to your app I can help debug?

**Comment by burkesimmons** [comment]
Well you're magic! It wasn't working for me until you signed in! Was I
supposed to wait 24 hours or something? Anyway, I should be able to get
what I need now.

Thanks!

Burke Simmons

**Comment by burkesimmons** [comment]
It's working now! Thanks.

**Comment by misbach** [comment]
that's weird. Glad it's working
